[package]
name = "udx"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Rust port of libudx, a protocol for reliable, multiplex, and congestion controlled streams over udp"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
documentation = "https://docs.rs/udx"
repository = "https://github.com/datrs/async-udx"
readme = "README.md"
keywords = ["udx", "p2p", "udp", "protocol"]
categories = [
  "asynchronous",
  "network-programming"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
tokio = { version = "1.21.2", features = ["net", "macros", "rt-multi-thread", "time", "io-util", "sync"] }
futures = "0.3.25"
tracing = "0.1.37"
bytes = "1.2.1"
log = "0.4.17"
udx-udp = { version = "0.2.0", path = "./udx-udp" }
atomic-instant = "0.1.1"
parking_lot = "0.12.1"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }
tracing-subscriber = "0.3.16"
pretty-bytes = "0.2.2"
# tests/ttl.rs reads the IP_TTL control message off a received datagram
libc = "0.2.69"

[[bench]]
name = "throughput"
harness = false

[features]
default = []
lock_tracking = []

[workspace]
members = ["udx-udp", "end-to-end"]
